name: Push Docker image
on:
  push:
    branches:
      - 'release/**'

jobs:
  push-front:
    permissions:
      contents: read
      packages: write

    uses: gunet/wallet-ecosystem/.github/workflows/docker-build-push.yml@dc-workflow
    secrets: inherit
    with:
      image-tag: ghcr.io/gunet/wallet-frontend:${GITHUB_REF#refs/heads/release/}
      docker-push: true
      dockerfile-path: ./Dockerfile
